import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';

const banner = `
/**
 * THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
 * if you want to view the source, please visit the github repository of this plugin
 * plugin: pure-chat-llm
 * version: ${process.env.npm_package_version}
 */`;
const prod = process.argv[2] === 'production';
console.log(`Building for ${prod ? 'production' : 'development'}...`);

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  metafile: prod,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

if (prod) {
  const result = await context.rebuild();

  // 3. Write the metafile to disk
  if (result.metafile) {
    fs.writeFileSync('meta.json', JSON.stringify(result.metafile, null, 2));
    console.log('Analysis metafile generated: meta.json');
  }

  process.exit(0);
} else {
  await context.watch();
}
